# Generated by Django 4.2.1 on 2023-05-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_alter_certification_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='detail',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='資格詳細'),
        ),
        migrations.AlterField(
            model_name='certificationrecord',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='certificationrecord',
            name='result',
            field=models.BooleanField(blank=True, null=True, verbose_name='結果'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='targetrecord',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='targetrecord',
            name='target_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='目標期限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='アイコン画像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instruction',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='自己紹介'),
        ),
    ]
